version: '3.7'

services:
  glpi-db:
    image: mysql:8.0
    container_name: glpi-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/volumes/glpi/mysql:/var/lib/mysql
    networks:
      - nginx-proxy
  glpi-web:
    build:
      context: .
    container_name: glpi-web
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - glpi-db
    volumes:
      - ./glpi:/var/www/html
      - ./glpi/files:/var/www/html/files
    networks:
      - nginx-proxy
    ports:
      - 8080:80

networks:
  nginx-proxy:
    # external: true
