version: '3.7'

services:
  glpi-db:
    image: mysql:8.0
    container_name: glpi-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - glpi-db-data:/var/lib/mysql
    networks:
      - nginx-proxy

  glpi-web:
    build:
      context: .
    container_name: glpi-web
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - glpi-db
    networks:
      - nginx-proxy
    volumes:
      - glpi-web-data:/var/www/html
      - glpi-data-files:/var/glpi/files

volumes:
  glpi-db-data:
  glpi-web-data:
  glpi-data-files:

networks:
  nginx-proxy:
    external: true
